caixabank:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: mpc-caixabank-ai
      location: europe-southwest1
      dataset: landing
      threads: 4
      timeout_seconds: 600
