# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x08pipeline\"\xdb\x01\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\x03\x12\x0f\n\x07\x63\x61rd_id\x18\x04 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x05 \x01(\t\x12\x10\n\x08use_chip\x18\x06 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x07 \x01(\x03\x12\x15\n\rmerchant_city\x18\x08 \x01(\t\x12\x16\n\x0emerchant_state\x18\t \x01(\t\x12\x0b\n\x03zip\x18\n \x01(\t\x12\x0b\n\x03mcc\x18\x0b \x01(\x03\x12\x0e\n\x06\x65rrors\x18\x0c \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=32
  _globals['_TRANSACTION']._serialized_end=251
# @@protoc_insertion_point(module_scope)
